<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Pack extends \AppBundle\Entity\Pack implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'publisher', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'image', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'publisheremail', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'publisherwebsite', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'privacypolicywebsite', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'licenseagreementwebsite', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'tags', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'size', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'enabled', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'review', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'premium', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'animated', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'whatsapp', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'signal', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'telegram', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'signalurl', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'telegramurl', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'downloads', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'created', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'stickers', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'categories', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'rates', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'tagslist', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'user', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'file', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'files');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'name', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'publisher', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'image', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'publisheremail', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'publisherwebsite', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'privacypolicywebsite', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'licenseagreementwebsite', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'tags', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'size', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'enabled', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'review', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'premium', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'animated', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'whatsapp', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'signal', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'telegram', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'signalurl', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'telegramurl', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'downloads', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'created', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'stickers', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'categories', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'rates', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'tagslist', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'user', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'file', '' . "\0" . 'AppBundle\\Entity\\Pack' . "\0" . 'files');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Pack $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublisher($publisher)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublisher', array($publisher));

        return parent::setPublisher($publisher);
    }

    /**
     * {@inheritDoc}
     */
    public function getPublisher()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublisher', array());

        return parent::getPublisher();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', array($image));

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', array());

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublisheremail($publisheremail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublisheremail', array($publisheremail));

        return parent::setPublisheremail($publisheremail);
    }

    /**
     * {@inheritDoc}
     */
    public function getPublisheremail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublisheremail', array());

        return parent::getPublisheremail();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublisherwebsite($publisherwebsite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublisherwebsite', array($publisherwebsite));

        return parent::setPublisherwebsite($publisherwebsite);
    }

    /**
     * {@inheritDoc}
     */
    public function getPublisherwebsite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublisherwebsite', array());

        return parent::getPublisherwebsite();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrivacypolicywebsite($privacypolicywebsite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrivacypolicywebsite', array($privacypolicywebsite));

        return parent::setPrivacypolicywebsite($privacypolicywebsite);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrivacypolicywebsite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrivacypolicywebsite', array());

        return parent::getPrivacypolicywebsite();
    }

    /**
     * {@inheritDoc}
     */
    public function setLicenseagreementwebsite($licenseagreementwebsite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLicenseagreementwebsite', array($licenseagreementwebsite));

        return parent::setLicenseagreementwebsite($licenseagreementwebsite);
    }

    /**
     * {@inheritDoc}
     */
    public function getLicenseagreementwebsite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLicenseagreementwebsite', array());

        return parent::getLicenseagreementwebsite();
    }

    /**
     * {@inheritDoc}
     */
    public function setEnabled($enabled)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnabled', array($enabled));

        return parent::setEnabled($enabled);
    }

    /**
     * {@inheritDoc}
     */
    public function getEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEnabled', array());

        return parent::getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function getStickers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStickers', array());

        return parent::getStickers();
    }

    /**
     * {@inheritDoc}
     */
    public function setStickers($stickers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStickers', array($stickers));

        return parent::setStickers($stickers);
    }

    /**
     * {@inheritDoc}
     */
    public function addSticker(\AppBundle\Entity\Sticker $sticker)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSticker', array($sticker));

        return parent::addSticker($sticker);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSticker(\AppBundle\Entity\Sticker $sticker)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSticker', array($sticker));

        return parent::removeSticker($sticker);
    }

    /**
     * {@inheritDoc}
     */
    public function getDownloadValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDownloadValue', array());

        return parent::getDownloadValue();
    }

    /**
     * {@inheritDoc}
     */
    public function getDownloads()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDownloads', array());

        return parent::getDownloads();
    }

    /**
     * {@inheritDoc}
     */
    public function setDownloads($downloads)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDownloads', array($downloads));

        return parent::setDownloads($downloads);
    }

    /**
     * {@inheritDoc}
     */
    public function getRates()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRates', array());

        return parent::getRates();
    }

    /**
     * {@inheritDoc}
     */
    public function setRates($rates)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRates', array($rates));

        return parent::setRates($rates);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\UserBundle\Entity\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFile', array());

        return parent::getFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setFile($file)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFile', array($file));

        return parent::setFile($file);
    }

    /**
     * {@inheritDoc}
     */
    public function getTags()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTags', array());

        return parent::getTags();
    }

    /**
     * {@inheritDoc}
     */
    public function setTags($tags)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTags', array($tags));

        return parent::setTags($tags);
    }

    /**
     * {@inheritDoc}
     */
    public function getPremiumValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPremiumValue', array());

        return parent::getPremiumValue();
    }

    /**
     * {@inheritDoc}
     */
    public function getPremium()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPremium', array());

        return parent::getPremium();
    }

    /**
     * {@inheritDoc}
     */
    public function setPremium($premium)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPremium', array($premium));

        return parent::setPremium($premium);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnimatedValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnimatedValue', array());

        return parent::getAnimatedValue();
    }

    /**
     * {@inheritDoc}
     */
    public function getAnimated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnimated', array());

        return parent::getAnimated();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnimated($animated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnimated', array($animated));

        return parent::setAnimated($animated);
    }

    /**
     * {@inheritDoc}
     */
    public function addCategory(\AppBundle\Entity\Category $category)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCategory', array($category));

        return parent::addCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategories', array());

        return parent::getCategories();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategories($categories)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategories', array($categories));

        return parent::setCategories($categories);
    }

    /**
     * {@inheritDoc}
     */
    public function getFiles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFiles', array());

        return parent::getFiles();
    }

    /**
     * {@inheritDoc}
     */
    public function setFiles($files)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFiles', array($files));

        return parent::setFiles($files);
    }

    /**
     * {@inheritDoc}
     */
    public function getReview()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReview', array());

        return parent::getReview();
    }

    /**
     * {@inheritDoc}
     */
    public function setReview($review)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReview', array($review));

        return parent::setReview($review);
    }

    /**
     * {@inheritDoc}
     */
    public function getReviewValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReviewValue', array());

        return parent::getReviewValue();
    }

    /**
     * {@inheritDoc}
     */
    public function addTagslist(\AppBundle\Entity\Tag $tagslist)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTagslist', array($tagslist));

        return parent::addTagslist($tagslist);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTagslist(\AppBundle\Entity\Tag $tagslist)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTagslist', array($tagslist));

        return parent::removeTagslist($tagslist);
    }

    /**
     * {@inheritDoc}
     */
    public function getTagslist()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTagslist', array());

        return parent::getTagslist();
    }

    /**
     * {@inheritDoc}
     */
    public function setTagslist($tagslist)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTagslist', array($tagslist));

        return parent::setTagslist($tagslist);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', array());

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated($created)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', array($created));

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getSize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSize', array());

        return parent::getSize();
    }

    /**
     * {@inheritDoc}
     */
    public function setSize($size)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSize', array($size));

        return parent::setSize($size);
    }

    /**
     * {@inheritDoc}
     */
    public function getSizes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSizes', array());

        return parent::getSizes();
    }

    /**
     * {@inheritDoc}
     */
    public function getNumbers($value)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumbers', array($value));

        return parent::getNumbers($value);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getWhatsapp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWhatsapp', array());

        return parent::getWhatsapp();
    }

    /**
     * {@inheritDoc}
     */
    public function getWhatsappValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWhatsappValue', array());

        return parent::getWhatsappValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setWhatsapp($whatsapp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWhatsapp', array($whatsapp));

        return parent::setWhatsapp($whatsapp);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelegram()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelegram', array());

        return parent::getTelegram();
    }

    /**
     * {@inheritDoc}
     */
    public function getTelegramValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelegramValue', array());

        return parent::getTelegramValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelegram($telegram)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelegram', array($telegram));

        return parent::setTelegram($telegram);
    }

    /**
     * {@inheritDoc}
     */
    public function getSignal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSignal', array());

        return parent::getSignal();
    }

    /**
     * {@inheritDoc}
     */
    public function getSignalValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSignalValue', array());

        return parent::getSignalValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setSignal($signal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSignal', array($signal));

        return parent::setSignal($signal);
    }

    /**
     * {@inheritDoc}
     */
    public function getSignalurl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSignalurl', array());

        return parent::getSignalurl();
    }

    /**
     * {@inheritDoc}
     */
    public function setSignalurl($signalurl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSignalurl', array($signalurl));

        return parent::setSignalurl($signalurl);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelegramurl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelegramurl', array());

        return parent::getTelegramurl();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelegramurl($telegramurl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelegramurl', array($telegramurl));

        return parent::setTelegramurl($telegramurl);
    }

}
