<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Settings extends \AppBundle\Entity\Settings implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'appname', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'appdescription', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'googleplay', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'privacypolicy', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'firebasekey', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'publisherid', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'appid', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'rewardedadmobid', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'banneradmobid', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'bannerfacebookid', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'nativebannerfacebookid', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'bannertype', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'nativeadmobid', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'nativefacebookid', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'nativeitem', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'nativetype', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'interstitialadmobid', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'interstitialfacebookid', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'interstitialtype', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'interstitialclick', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'file', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'media');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'appname', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'appdescription', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'googleplay', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'privacypolicy', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'firebasekey', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'publisherid', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'appid', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'rewardedadmobid', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'banneradmobid', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'bannerfacebookid', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'nativebannerfacebookid', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'bannertype', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'nativeadmobid', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'nativefacebookid', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'nativeitem', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'nativetype', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'interstitialadmobid', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'interstitialfacebookid', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'interstitialtype', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'interstitialclick', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'file', '' . "\0" . 'AppBundle\\Entity\\Settings' . "\0" . 'media');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Settings $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAppname($appname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAppname', array($appname));

        return parent::setAppname($appname);
    }

    /**
     * {@inheritDoc}
     */
    public function getAppname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAppname', array());

        return parent::getAppname();
    }

    /**
     * {@inheritDoc}
     */
    public function setAppdescription($appdescription)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAppdescription', array($appdescription));

        return parent::setAppdescription($appdescription);
    }

    /**
     * {@inheritDoc}
     */
    public function getAppdescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAppdescription', array());

        return parent::getAppdescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setGoogleplay($googleplay)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGoogleplay', array($googleplay));

        return parent::setGoogleplay($googleplay);
    }

    /**
     * {@inheritDoc}
     */
    public function getGoogleplay()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGoogleplay', array());

        return parent::getGoogleplay();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrivacypolicy($privacypolicy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrivacypolicy', array($privacypolicy));

        return parent::setPrivacypolicy($privacypolicy);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrivacypolicy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrivacypolicy', array());

        return parent::getPrivacypolicy();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirebasekey($firebasekey)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirebasekey', array($firebasekey));

        return parent::setFirebasekey($firebasekey);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirebasekey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirebasekey', array());

        return parent::getFirebasekey();
    }

    /**
     * {@inheritDoc}
     */
    public function getFile()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFile', array());

        return parent::getFile();
    }

    /**
     * {@inheritDoc}
     */
    public function setFile($file)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFile', array($file));

        return parent::setFile($file);
    }

    /**
     * {@inheritDoc}
     */
    public function setMedia(\MediaBundle\Entity\Media $media)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMedia', array($media));

        return parent::setMedia($media);
    }

    /**
     * {@inheritDoc}
     */
    public function getMedia()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMedia', array());

        return parent::getMedia();
    }

    /**
     * {@inheritDoc}
     */
    public function getBanneradmobid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBanneradmobid', array());

        return parent::getBanneradmobid();
    }

    /**
     * {@inheritDoc}
     */
    public function setBanneradmobid($banneradmobid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBanneradmobid', array($banneradmobid));

        return parent::setBanneradmobid($banneradmobid);
    }

    /**
     * {@inheritDoc}
     */
    public function getBannerfacebookid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBannerfacebookid', array());

        return parent::getBannerfacebookid();
    }

    /**
     * {@inheritDoc}
     */
    public function setBannerfacebookid($bannerfacebookid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBannerfacebookid', array($bannerfacebookid));

        return parent::setBannerfacebookid($bannerfacebookid);
    }

    /**
     * {@inheritDoc}
     */
    public function getNativefacebookid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNativefacebookid', array());

        return parent::getNativefacebookid();
    }

    /**
     * {@inheritDoc}
     */
    public function setNativefacebookid($nativefacebookid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNativefacebookid', array($nativefacebookid));

        return parent::setNativefacebookid($nativefacebookid);
    }

    /**
     * {@inheritDoc}
     */
    public function getNativeadmobid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNativeadmobid', array());

        return parent::getNativeadmobid();
    }

    /**
     * {@inheritDoc}
     */
    public function setNativeadmobid($nativeadmobid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNativeadmobid', array($nativeadmobid));

        return parent::setNativeadmobid($nativeadmobid);
    }

    /**
     * {@inheritDoc}
     */
    public function getInterstitialfacebookid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInterstitialfacebookid', array());

        return parent::getInterstitialfacebookid();
    }

    /**
     * {@inheritDoc}
     */
    public function setInterstitialfacebookid($interstitialfacebookid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInterstitialfacebookid', array($interstitialfacebookid));

        return parent::setInterstitialfacebookid($interstitialfacebookid);
    }

    /**
     * {@inheritDoc}
     */
    public function getInterstitialadmobid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInterstitialadmobid', array());

        return parent::getInterstitialadmobid();
    }

    /**
     * {@inheritDoc}
     */
    public function setInterstitialadmobid($interstitialadmobid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInterstitialadmobid', array($interstitialadmobid));

        return parent::setInterstitialadmobid($interstitialadmobid);
    }

    /**
     * {@inheritDoc}
     */
    public function getBannertype()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBannertype', array());

        return parent::getBannertype();
    }

    /**
     * {@inheritDoc}
     */
    public function setBannertype($bannertype)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBannertype', array($bannertype));

        return parent::setBannertype($bannertype);
    }

    /**
     * {@inheritDoc}
     */
    public function getInterstitialtype()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInterstitialtype', array());

        return parent::getInterstitialtype();
    }

    /**
     * {@inheritDoc}
     */
    public function setInterstitialtype($interstitialtype)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInterstitialtype', array($interstitialtype));

        return parent::setInterstitialtype($interstitialtype);
    }

    /**
     * {@inheritDoc}
     */
    public function getNativetype()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNativetype', array());

        return parent::getNativetype();
    }

    /**
     * {@inheritDoc}
     */
    public function setNativetype($nativetype)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNativetype', array($nativetype));

        return parent::setNativetype($nativetype);
    }

    /**
     * {@inheritDoc}
     */
    public function getInterstitialclick()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInterstitialclick', array());

        return parent::getInterstitialclick();
    }

    /**
     * {@inheritDoc}
     */
    public function setInterstitialclick($interstitialclick)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInterstitialclick', array($interstitialclick));

        return parent::setInterstitialclick($interstitialclick);
    }

    /**
     * {@inheritDoc}
     */
    public function getNativeitem()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNativeitem', array());

        return parent::getNativeitem();
    }

    /**
     * {@inheritDoc}
     */
    public function setNativeitem($nativeitem)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNativeitem', array($nativeitem));

        return parent::setNativeitem($nativeitem);
    }

    /**
     * {@inheritDoc}
     */
    public function getRewardedadmobid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRewardedadmobid', array());

        return parent::getRewardedadmobid();
    }

    /**
     * {@inheritDoc}
     */
    public function setRewardedadmobid($rewardedadmobid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRewardedadmobid', array($rewardedadmobid));

        return parent::setRewardedadmobid($rewardedadmobid);
    }

    /**
     * {@inheritDoc}
     */
    public function getNativebannerfacebookid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNativebannerfacebookid', array());

        return parent::getNativebannerfacebookid();
    }

    /**
     * {@inheritDoc}
     */
    public function setNativebannerfacebookid($nativebannerfacebookid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNativebannerfacebookid', array($nativebannerfacebookid));

        return parent::setNativebannerfacebookid($nativebannerfacebookid);
    }

    /**
     * {@inheritDoc}
     */
    public function getPublisherid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublisherid', array());

        return parent::getPublisherid();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublisherid($publisherid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublisherid', array($publisherid));

        return parent::setPublisherid($publisherid);
    }

    /**
     * {@inheritDoc}
     */
    public function getAppid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAppid', array());

        return parent::getAppid();
    }

    /**
     * {@inheritDoc}
     */
    public function setAppid($appid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAppid', array($appid));

        return parent::setAppid($appid);
    }

}
